version: "3.8"
services:
  medusa:
    build:
      dockerfile: Dockerfile.medusa
    depends_on:
      - postgres

  storefront:
    build:
      dockerfile: Dockerfile.storefront
    depends_on:
      - medusa

  postgres:
    image: postgres
    expose:
      - "5432"
    volumes:
      - /var/lib/postgresql/data
